"""empty message

Revision ID: 585b523084e7
Revises: a2cbd83a09cb
Create Date: 2022-01-07 00:25:02.593088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585b523084e7'
down_revision = 'a2cbd83a09cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_on', sa.DateTime(), nullable=False),
    sa.Column('user_id_fk', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_calls')
    # ### end Alembic commands ###
