"""empty message

Revision ID: 5c1eae6fa7fa
Revises: 
Create Date: 2021-12-24 00:53:50.317910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1eae6fa7fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('model_type', sa.String(length=80), nullable=False))
    op.add_column('task', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('task', sa.Column('finished_on', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('model_id', sa.String(), nullable=True))
    op.add_column('task', sa.Column('model_name_fk', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'task', 'models', ['model_name_fk'], ['model_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'model_name_fk')
    op.drop_column('task', 'model_id')
    op.drop_column('task', 'finished_on')
    op.drop_column('task', 'created_on')
    op.drop_column('models', 'model_type')
    # ### end Alembic commands ###
