"""empty message

Revision ID: 86e5f349b756
Revises: 500d137d9396
Create Date: 2022-01-01 16:59:48.222272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e5f349b756'
down_revision = '500d137d9396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id_fk', sa.String(length=80), nullable=True))
        batch_op.create_foreign_key(None, 'models', ['model_id_fk'], ['model_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('model_id_fk')

    # ### end Alembic commands ###
