"""empty message

Revision ID: 884790144d85
Revises: 9f701d27c5f4
Create Date: 2021-12-26 16:05:07.368855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884790144d85'
down_revision = '9f701d27c5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'models', ['model_id_fk'], ['model_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id_fk'], ['id'])
        batch_op.drop_column('model_name_fk')
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('model_name_fk', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'models', ['model_name_fk'], ['model_name'])

    # ### end Alembic commands ###
