"""empty message

Revision ID: c1c487701ebe
Revises: 86e5f349b756
Create Date: 2022-01-04 23:06:28.181190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c487701ebe'
down_revision = '86e5f349b756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.String(length=80), nullable=True),
    sa.Column('role_type', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
